export class CandidatureDetails {
    id:string;
	roleOfResponsibilities:string;
	positionLocation:string;
	candidateName:string;
	contactNo:string;
	emailId:string;
	totalExperience:string;
	relevantExperience:string;
	noticePeriod:string;
	currentLocation:string;
	preferredLocation:string;
	modeOfHiring:string;
	vendorName:string;
	profileSharedDate:string;
	screeningStatus:string;
	screeningDate:string
	screeningDoneBy:string;
	firstRoundStatus:string;
	firstRoundDate:string
	firstRoundTakenBy:string;
	secondRoundStatus:string;
	secondRoundDate:string
	secondRoundTakenBy:string;
	finalRoundStatus:string;
	finalRoundDate:string
	finalRoundTakenBy:string;
	hrOrPnStageRound:string;
	hrOrPnStageStatus:string;
	hrOrPnStageDate:string
	candidatureStatus:string;
	offerRollOutDate:string
	joiningDate:string
	joiningStatus:string;
	nhrId:string;
	comments:string;
	action:string;
	client:string;
	profile:string;
	lastUpdateDate:string
       
}