export default {
    "roleOfResponsibilities": "Role",
    "positionLocation": "Position Loc",
    "candidateName": "Candidate Name",
    "contactNo": "Phone",
    "emailId": "Email",
    "totalExperience": "Total Exp",
    "relevantExperience": "Relavant Exp",
    "noticePeriod": "Notice Period",
    "currentLocation": "Current Loc",
    "preferredLocation": "Preferred Loc",
    "modeOfHiring": "Mode of Hiring",
    "vendorName": "Vendor Name",
    "profileSharedDate": "Profile Shared Date",
    "screeningStatus": "Screening Status",
    "screeningDate": "Screening Date",
    "screeningDoneBy": "Screening Done By",
    "firstRoundStatus": "First Round Status",
    "firstRoundDate": "First Round Date",
    "firstRoundTakenBy": "First Round Done By",
    "secondRoundStatus": "Second Round Status",
    "secondRoundDate": "Second Round Date",
    "secondRoundTakenBy": "Second Round Done By",
    "finalRoundStatus": "Final Round Status",
    "finalRoundDate": "Final Round Date",
    "finalRoundTakenBy": "Final Round Done By",
    "hrOrPnStageRound": "HR/PN Stage Round",
    "hrOrPnStageStatus": "HR/PN Stage Status",
    "hrOrPnStageDate": "HR/PN Stage Date",
    "candidatureStatus": "Candidature Status",
    "offerRollOutDate": "Offer Rollout Date",
    "joiningDate": "Joining Date",
    "joiningStatus": "Joining Status",
    "nhrId": "NHR ID",
    "comments": "Comments",
    "action": "Action Pending",
    "client": "Client",
    "profile": "Profile Status",
    "lastUpdateDate": "Last Upated On"
}